apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
  namespace: development  # ✅ Ensure the correct namespace
spec:
  replicas: 3
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
      - name: flask-app
        image: ${IMAGE_TAG}  # ✅ Placeholder for dynamic substitution
        ports:
        - containerPort: 8000  # ✅ Ensure it matches your Flask app